import typing
from pydantic import Field
from openenv.core.env_server.types import Action, Observation

class GridAction(Action):
    """Actions for the NeonGrid AI Architect."""
    consumption_mode: str = Field(..., description="Mode: 'low', 'normal', 'high' - Affects comfort and energy use.")
    battery_mode: str = Field(..., description="Mode: 'charge', 'discharge', 'idle' - Manages energy storage.")
    source_priority: str = Field(..., description="Priority: 'solar', 'grid' - Where to pull energy from first.")

class GridObservation(Observation):
    """Observations from the NeonGrid environment."""
    grid_price: float = Field(..., description="Current cost of electricity per unit from the main grid.")
    solar_output: float = Field(..., description="Current power being generated by district solar arrays.")
    battery_level: float = Field(..., description="Current charge percentage of the district battery (0-100).")
    district_demand: float = Field(..., description="Real-time power demand from citizens.")
    comfort_index: float = Field(..., description="Happiness levels of citizens (0.0 to 1.0).")
    weather: str = Field(..., description="Current weather condition: 'sunny', 'cloudy', 'stormy'.")
    status_message: str = Field(..., description="Feedback from the grid controller.")
    current_time: str = Field(..., description="Simulated time in the district (HH:MM).")
    directives: typing.Optional[str] = Field(None, description="Current instructions from the Human Architect.")
